---
- name: Sending mail notification
  hosts: all

  collections:
    community.general.mail

  roles:
    - role: sent_mail
      vars:
        email_username: '{{ lookup("env", "email_username") }}'
        email_password: '{{ lookup("env", "email_password") }}'
        recipient: "{{ recipient }}"
        subject: "{{ subject }}"
        body: "{{ body }}"
