---

- name: Detect EC2 state
  hosts: localhost

  sources:
    - ansible.eda.aws_cloudtrail:
        access_key: "{{ aws_access_key_id }}"
        secret_key: "{{ aws_secret_access_key }}"
        region: 'us-east-2'

  rules:
    - name: Monitor StopInstances Events
      condition: event.CloudTrailEvent.eventName == "StopInstances"
      action:
        run_workflow_template:
          name: create_servicenow_incident
          organization: Cloud_Team
          job_args:
            extra_vars:
              ansible_eda: "{{ event.CloudTrailEvent }}"
