---
- name: ServiceNow Webhook trigger
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        port: 5001

  rules:
    - name: Call ServiceNow Workflow
      condition: event.payload.description is defined
      action:
        run_job_template:
          name: snow_event_workflow
          organization: Cloud_Team
          extra_vars:
            ansible_eda: "{{ event.payload.message }}"
