---
# tasks file for sent_mail
- name: Sending an e-mail using Gmail SMTP servers
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    sender: "{{ email_username }}"
    to: "{{ recipient }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    subject: "{{ subject }}"
    body: "{{ body }}"
