---

- name: Handle EC2 state Shutdown
  hosts: localhost

  tasks:

    - name: Debug full event
      ansible.builtin.debug:
        var: ansible_eda

    # - name: Print event details
    #   ansible.builtin.debug:
    #     msg: "EC2 instance {{ ansible_eda['event']['CloudTrailEvent']['requestParameters']['instancesSet']['items'][0]['instanceId'] }} stopped at {{ ansible_eda.event.CloudTrailEvent.eventTime }}"

    - name: Restart instance if stopped
      amazon.aws.ec2_instance:
        region: us-east-2
        instance_ids:
          - "{{ ansible_eda['event']['CloudTrailEvent']['requestParameters']['instancesSet']['items'][0]['instanceId'] }}"
        state: running
