---

- name: Handle EC2 instance shutdown
  hosts: localhost

  tasks:

    - name: Debug full event
      ansible.builtin.debug:
        var: ec2_event

    - name: Print event details
      ansible.builtin.debug:
        msg: "EC2 instance {{ ec2_event.requestParameters.instanceId }} stopped at {{ ansible_eda.event.CloudTrailEvent.eventTime }}"
