---

- name: Restart an EC2 instance
  hosts: localhost

  tasks:
    - name: Restart instance if stopped
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids:
          - "{{ instance_id }}"
        state: running
