---

- name: Restart an EC2 instance
  hosts: localhost

  vars:
    instance_id: "c"
    region: us-east-2

  tasks:

    - name: Restart instance if stopped
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids:
          - "{{ instance_id }}"
        state: running
